env:
    es2021: true
    node: true
extends:
    - xo
    - xo-react
    - xo-typescript
    - prettier
    - next/core-web-vitals
rules:
    no-console: "error"
    capitalized-comments: "off"
    new-cap:
        - error
        - capIsNew: false
    react/function-component-definition: "off"
    react/display-name: "off"
    "@typescript-eslint/triple-slash-reference": "off"
    "@typescript-eslint/consistent-type-imports":
        - warn
        - prefer: type-imports
    "@typescript-eslint/naming-convention":
        - warn
        - selector: variable
          format:
              - PascalCase
              - camelCase
              - UPPER_CASE

parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
