server:
  port: 3000
me:
  github: "Hexiro"
  twitter: "Hexiiro"
  birthday: "2005-07-02T00:00:00Z"
messages:
  404:
    - "what is this?"
    - "where am i?"
    - "how have you found this place?"
    - "stay out!"
    - "you're not supposed to be here!"
  500:
    - "well this wasn't expected"
    - "uhhhhhhhhhhhhhhhh"
    - "something unexpected happened :shrug:"
    - "oops?"
    - "is this issue worth reporting?"