export interface Project {
    name: string;
    description: string;
    href: string;
}

// TODO: maybe make this fetched at build time? not sure how that would work with vercel
export const Projects: Project[] = [
    {
        name: "autorequests",
        description:
            "Automatically create a simple API wrapper from request data generated by your browser.",
        href: "https://github.com/Hexiro/autorequests",
    },
    {
        name: "herokron",
        description:
            "Herokron is a python package used to make switching Heroku apps on/off easy, especially between accounts. The primary use case is from the command line / as a cron job",
        href: "https://github.com/Hexiro/herokron",
    },
    {
        name: "imperialbin/imperial-py",
        description: "Official Python API wrapper for https://imperialb.in",
        href: "https://github.com/imperialbin/imperial-py",
    },
];
